# Generated by Django 4.2.1 on 2023-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(max_length=255)),
                ('db_driver', models.CharField(max_length=255)),
                ('db_host', models.CharField(max_length=255)),
                ('db_port', models.CharField(max_length=255)),
                ('db_database', models.CharField(max_length=255)),
                ('db_username', models.CharField(max_length=255)),
                ('db_password', models.CharField(max_length=255)),
                ('db_unix_socket', models.CharField(blank=True, max_length=255, null=True)),
                ('db_charset', models.CharField(blank=True, max_length=255, null=True)),
                ('db_collation', models.CharField(blank=True, max_length=255, null=True)),
                ('db_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('db_prefix_indexes', models.BooleanField(default=True)),
                ('db_strict', models.BooleanField(default=True)),
                ('db_engine', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_key', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_region', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket_endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('public_storage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
